name: Build HW3D

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:      
  build:
    name: Build
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x86, x64]

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: MSBuild
      working-directory: ${{ github.workspace }}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}

    - name: Create artifact release directory
      run: |
        $sourcePath = "${{ github.workspace }}\bin"
        $destinationPath = "${{ github.workspace }}\artifacts"

        # Create the destination directory if it doesn't exist
        if (-not (Test-Path -Path $destinationPath)) {
          New-Item -ItemType Directory -Path $destinationPath
        }

        # Get all .exe, .pdb, and .cso files from the platform/configuration directories
        Get-ChildItem -Path $sourcePath -Recurse -File -Include *.exe, *.pdb, *.cso -Exclude vc143.pdb | Where-Object {
          $_.DirectoryName -match '\\(Win32|x64)\\Release|Debug)$'
        } | ForEach-Object {
          Copy-Item -Path $_.FullName -Destination $destinationPath -Force
        }

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HW3D-${{ matrix.platform }}-${{ matrix.configuration }}
        path: ${{ github.workspace }}\artifacts\*
        if-no-files-found: error
        retention-days: 1
